### ISSUE TITLE
请问AR挖矿数据在哪里下载？

### ISSUE THREAD

**Issue by inSight-mk1** [hpool-dev/arweave-miner#1]
官方客服微信加不了，近期被太多人添加，微信直接不让加好友了。发邮件也没人回复。

**Comment by azhe** [comment]
同问 and 同样加不上客服

**Comment by qazwsxee1130** [comment]
對呀 現在都沒有挖礦數據
新人要怎麼入池?

**Comment by inSight-mk1** [comment]
@hpool-dev

**Comment by inSight-mk1** [comment]
> ![image](https://user-images.githubusercontent.com/13961675/120424986-01f5c600-c3a0-11eb-913d-45895cf85ea4.png)
> 
> Discord HPOOL ：[FHEsvEczQJ](https://discord.gg/FHEsvEczQJ)
> 
> 我找到在哪下載了
> 
> 這邊翻一下ar-pool討論的紀錄就有了

Thanks a lot. It works.

**Comment by inSight-mk1** [comment]
Since we found AR data on Discord HPOOL, I am closing this issue.
在HPOOL的Discord上找到AR数据的下载地址了，因此关闭这个issue。
